[package]
name = "rs2048"
version = "0.1.0"
authors = ["sanyi"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ncurses = "5.99.0"
rand = "0.7.3"